# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      localstack: 
        image: localstack/localstack:0.11.1
        ports: 
          - 4567:4597
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Python
      uses: actions/setup-python@v2.2.1
    - run: sudo apt-get install -y python3-pip
    - run: yes | pip install awscliv2
    - run: yes json | aws configure || true
    - run: npm i -g yarn
    - run: yarn
    - run: npm test
      env: 
       ENVIRONMENT: CI
       USE_ENV_VARIABLES: "TRUE"
       FAKE_SQL_USERNAME: MAF
       FAKE_SQL_PASSWORD: MAF
     
    - name: Status Create Action
      if: ${{ always() }}
      uses: hkusu/status-create-action@v1.0.0
      id: status-create
      with:
        state: ${{ job.status }} 
        sha: ${{ github.sha }}
  
    - name: Show result
      if: always()
      run: echo '${{ steps.status-create.outputs.result }}'
